development:
 api_key: 442c6504bd2362d8a7fba7303cd583ca 
 secret_key: XXXXXXXXXXXXX
 canvas_page_name: facebooker_tutorial    
 callback_url: http://staging.travelerstable.com:8888
 tunnel:
     public_host_username: fooberryfoo 
     public_host: staging.travelerstable.com
     public_port: 8888
     local_port: 3000    

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 40